name: Terraform Cloud Github actions Workflow

on:
  push:
    branches:
      - main

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:      
  
 jobs:
    terraform:
      runs-on: ubuntu-latest
  
      steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
  
      - name: Set up Terraform CLI
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.5
  
      - name: Configure Terraform Cloud
        run: |
          echo "credentials \"$<your-organization-name>\" { token = \${{ secrets.TF_API_TOKEN }} }" >> ~/.terraformrc
          terraform init -backend-config="organization=<your-organization-name>" -backend-config="workspace=<your-workspace-name>"
  
      - name: Terraform Plan
        run: terraform plan -out=tfplan
  
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        env:
          ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
          ARM_ENVIRONMENT: "public"
  
    # Add secrets to your GitHub repository:
    # - TF_API_TOKEN: Your Terraform Cloud API token
    # - ARM_CLIENT_ID: Your Azure Service Principal client ID
    # - ARM_CLIENT_SECRET: Your Azure Service Principal client secret
    # - ARM_SUBSCRIPTION_ID: Your Azure subscription ID
    # - ARM_TENANT_ID: Your Azure AD tenant ID
  



      
