name: Terraform Cloud Workflow

on:
  push:
    branches:
      - main

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:      

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.6.5
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Check Terraform version
      run: terraform version    
      

    - name: Login to Azure
      run: az login --service-principal -u ${{ secrets.CLIENT_ID }} -p ${{ secrets.CLIENT_SECRET }} --tenant ${{ secrets.TENANT_ID }}    

    - name: Configure Terraform Cloud
      run: |
        echo "credentials \"$TF_CLOUD_WORKSPACE_NAME\" { \n  token = \"$TF_CLOUD_API_TOKEN\" \n}" > $GITHUB_WORKSPACE/.terraformrc
      env:
        TF_CLOUD_WORKSPACE_NAME: dev-workspace
        TF_CLOUD_API_TOKEN: ${{ secrets.TF_API_TOKEN }}  
     
    - name: Debugging
      run: |
          cat $GITHUB_WORKSPACE/.terraformrc
          echo "TF_CLOUD_WORKSPACE_NAME: $TF_CLOUD_WORKSPACE_NAME"
          echo "TF_CLOUD_API_TOKEN: $TF_CLOUD_API_TOKEN"    

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      run: terraform apply tfplan  
  
    - name: Terraform Show
      run: terraform show



      
